config/routes.rb
Rails.application.routes.draw do
  get "/sync", to: "reports#sync"
  get "/export", to: "reports#export"
  root 'static_pages#home'
  devise_for :admins
  resources :reports do
    resources :comments, only: [:new, :create]
  end
  resources :placements, only: [:index]
  get '/retrieve', to: 'placements#retrieve'
  get '/export_placements', to: 'placements#export_placements'
  
  
end

app/models/report.rb
class Report < ApplicationRecord
    has_many :comments
    def self.to_csv
        attributes = %w{month days salary_earned client sector}
    
        CSV.generate(headers: true) do |csv|
          csv << attributes
    
          all.each do |report|
            csv << attributes.map{ |attr| report.send(attr) }
          end
        end
      end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authorized?
  require 'csv'
  def sync
      url = "https://marketplace-app-sj.herokuapp.com/api/v1/reports?api_user=Reporting_app&token=#{ENV["KEY"]}"
      p url
      response = RestClient.get(url)
      @placements = JSON.parse(response)
      @placements.each do |placement|
        last_report = Report.last
          if !last_report.nil? 
            if last_report.placement_id < placement['id']
              start_date=placement['start_date'].to_date
              end_date=placement['end_date'].to_date
              salary=placement['monthly_salary']
              placement_id=placement['id']
              client =placement['client']['name']
              sector =placement['job_request']['category']
              placement_id=placement['id']
              months = array_of_months(start_date, end_date)
              days = array_of_days(start_date, end_date)
              (0..(months.length-1)).each do |i|
                salary_earned = ((salary.to_f)/30)*days[i]
                if Report.where(client: client).find_by(month:months[i])
                  @report = Report.where(client: client).find_by(month:months[i])
                  puts @report.id
                  new_salary = @report.salary_earned + salary_earned
                  new_days = @report.days + days[i]
                  @report.update(salary_earned: new_salary, days: new_days)
                else
                  Report.create!(days: days[i], month: months[i], salary_earned: salary_earned, client: client, sector: sector, placement_id: placement_id)
                end
              end
            else 
              flash[:info] = "There aren't new reports" 
              # redirect_to request.referer
            end
          else
            start_date=placement['start_date'].to_date
            end_date=placement['end_date'].to_date
            salary=placement['monthly_salary']
            placement_id=placement['id']
            client =placement['client']['name']
            sector =placement['job_request']['category']
            placement_id=placement['id']
            months = array_of_months(start_date, end_date)
            days = array_of_days(start_date, end_date)
            (0..(months.length-1)).each do |i|
              salary_earned = ((salary.to_f)/30)*days[i]
              Report.create!(days: days[i], month: months[i], salary_earned: salary_earned, client: client, sector: sector, placement_id: placement_id)
            end
        end
      end
    redirect_to reports_path
  end

def show
  @report=Report.find(params[:id])
    @comments = @report.comments
end

def export
  if params[:commit].nil?
    @reports=Report.all
    respond_to do |format|
    format.html
    format.csv { send_data @reports.to_csv, filename: "reports-#{Date.today}.csv" }
    end
  else
      if !params[:client].nil?
        @reports=Report.where("client= ?", params[:client])
        respond_to do |format|
          format.html
          format.csv { send_data @reports.to_csv, filename: "reports-#{Date.today}.csv" }
          end 
      elsif !params[:month].nil?
        @reports=Report.where("month= ?", params[:month])
        respond_to do |format|
          format.html
          format.csv { send_data @reports.to_csv, filename: "reports-#{Date.today}.csv" }
          end
      elsif !params[:category].nil?
        @reports=Report.where("sector= ?", params[:category])
        respond_to do |format|
          format.html
          format.csv { send_data @reports.to_csv, filename: "reports-#{Date.today}.csv" }
          end   
      end
  end
  
end


 def index
    if !params[:commit].nil?
      if params[:category] 
      @reports=Report.where("sector= ?", params[:category])
      elsif params[:client]
      @reports=Report.where("client= ?", params[:client])
      elsif params[:month]
      @reports=Report.where("month= ?", params[:month])
      end
    else
      @reports=Report.all
    end
  end
  private

    def array_of_months(start_date,end_date)
      from = start_date
      to = end_date
      (from..to).group_by {|a| [a.year, a.month]}.map do |group|
        group.first.last
      end
    end
 
    def array_of_days(start_date, end_date)
      from = start_date
      to = end_date
      (from..to).group_by {|a| [a.year, a.month]}.map do |group|
        group.last.length
      end
    end

    def authorized?
      return unless !current_admin
      flash[:danger]="Access denied"
      redirect_to root_path
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/index.html.erb
<%= link_to "Retrieve reports", sync_path , class:'retrieve-button'%><br/>
<br/>
<%= link_to "Undo Filters", reports_path %>
<h2> Reports </h2>
<table class="table">
  <thead>
    <tr>

    <%= form_with url: "/reports", method: :get do |form| %>
      <th scope="col">#</th>
      <th scope="col"><%= form.label :Month %><br/><%= form.select :month, Report.group(:month).count.keys%>
                      <%= form.submit "Filter by month", class: "btn btn-primary" %>
                      <%end%>
      </th>
      <%= form_with url: "/reports", method: :get do |form| %>
      <th scope="col">Days Worked</th>
      <th scope="col"><%= form.label :Client %><br/><%= form.select :client, Report.group(:client).count.keys%>
                      <%= form.submit "Filter by client", class: "btn btn-primary" %>
                      <%end%>
      </th>
    <%= form_with url: "/reports", method: :get do |form| %>
      <th scope="col">Total Factured</th>
      <th scope="col"><%= form.label :Category %><br/>
      <%= form.select :category, ['Logistics', 'Tech', 'Driving', 'Distribution', 'Sales', 'Other']%>
                      <%= form.submit "Filter by category", class: "btn btn-primary" %>
                      <%end%>
      </th>
    </tr>
  </thead>
  <% @reports.each do |report|%>
  <tbody>
    <tr>
      <th scope="row"><%=report.id%></th>
      <td><%=Date::MONTHNAMES[report.month]%></td>
      <td><%=report.days%></td>
      <td><%=report.client%></td>
      <td><%=report.salary_earned.round(2)%></td>
      <td><%=report.sector%></td>
      <td><%= link_to "Show", report_path(report.id)%></td>
    </tr>
  <%end%>
  <tbody>
    <tr>
      <th scope="row">Total</th>
      <td></td>
      <td></td>
      <td></td>
      <td><% total_to_be_factured=0%>
          <% @reports.each do |report|%>
          <% total_to_be_factured+=report.salary_earned%>
          <%end%>
          <%=total_to_be_factured.round(2)%></td>
      <td></td>
    </tr>

  </tbody>
</table>

<% if params[:commit].nil?%>
  <%= link_to "Export", export_path(format: 'csv'),class: "btn btn-primary" %>
<% else%>
    <% if !params[:client].nil? %>
      <%= form_with url: export_path(format: 'csv'), method: :get do |form| %>
      <%= hidden_field_tag :client, params[:client]%>
      <%= form.submit "Export!!", class: "btn btn-primary" %>
      <% end %>
    <% elsif !params[:month].nil? %>
      <%= form_with url: export_path(format: 'csv'), method: :get do |form| %>
      <%= hidden_field_tag :month, params[:month]%>
      <%= form.submit "Export!!", class: "btn btn-primary" %>
      <% end %>
    <% elsif !params[:category].nil? %>
      <%= form_with url: export_path(format: 'csv'), method: :get do |form| %>
      <%= hidden_field_tag :category, params[:category]%>
      <%= form.submit "Export!!", class: "btn btn-primary" %>
      <% end %>
    <% end %>
<% end %>

app/views/reports/show.html.erb
<div class='container report-show'>
  <h1>Report for <%=@report.client%> for the month of <%=Date::MONTHNAMES[@report.month]%></h1>
  <div class= "col-md-8 col-md-offset-2">
    <table class='table'>
      <tr>
        <th>Month</th>
        <th>Days</th>
        <th>Client</th>
        <th>Factured</th>
        <th>Sector</th>
      </tr>
      <tr>
      <td><%=@report.month%></td>
      <td><%=@report.days%></td>
      <td><%=@report.client%></td>
      <td><%=@report.salary_earned%></td>
      <td><%=@report.sector%></td>
      </tr>
    </table>
  </div>  
  <div class='comments'>
    <h3>Comments</h3>
    <%@comments.each do |comment| %>
    <div class='comment-card'>
      <p><%=comment.content%></p>
      </div>
    <%end%>
    <%= form_for ([@report, Comment.new]) do |f| %>
      <div class="field">
          <%= f.text_area :content, placeholder: "Add new comment..." %>
      </div>
      <%= f.submit "Post", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

    
    

 